-- AlterEnum
ALTER TYPE "SaleStatus" ADD VALUE IF NOT EXISTS 'DITERIMA';
ALTER TYPE "SaleStatus" ADD VALUE IF NOT EXISTS 'HILANG';
ALTER TYPE "SaleStatus" ADD VALUE IF NOT EXISTS 'RETURN';

-- AlterTable
ALTER TABLE "Sale" ALTER COLUMN "status" SET DEFAULT 'DITERIMA';
